# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180810_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '专题课'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name_plural': '课程详细'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name_plural': '课时'},
        ),
        migrations.AlterModelOptions(
            name='oftenaskedquestion',
            options={'verbose_name_plural': '常见问题'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '讲师'},
        ),
    ]
