# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user_usertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': 'UserToken'},
        ),
    ]
